40 cardable
GioSF/api pull request #44
Opened 2021-09-13 19:48 UTC by thalesAlves758

2021-10-17 04:26 UTC, giosf requested changes

2021-10-17 04:26 UTC, giosf commented on app/Models/Card.php
> +	public function cardable()
@thalesAlves758 Acho que esse método pode ser movido para o trait HasCards. Fica mais prático.

2021-10-17 17:57 UTC, thalesAlves758 commented on app/Models/Card.php
> +	public function cardable()
@GioSF Mudanças realizadas

2021-10-18 03:54 UTC, giosf commented on app/Models/Card.php
> +	public function cardable()
@thalesAlves758 massa, obrigado!

2021-11-08 07:03 UTC, merged